add version check

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -61,31 +61,31 @@ jobs:
       - name: Test
         run: python -m unittest
 
-  # check-version-bump:
-  #   if: github.ref == 'refs/heads/main'
-  #   runs-on: ubuntu-latest
-  #   needs: [ruff-check, test]
-  #   
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #
-  #     - name: Load PyPI version
-  #       uses: maybe-hello-world/pyproject-check-version@v4
-  #       id: version_check
-  #     
-  #     - name: check output
-  #       run: |
-  #         if [ "${{ steps.version_check.outputs.local_version_is_higher }}" ]; then
-  #           local=${{ steps.versioncheck.outputs.local_version }}
-  #           pypi=${{ steps.versioncheck.outputs.local_version }}
-  #         echo "Error: local version($local) is lower than the PyPI($pypi), bump it to publish"
-  #           exit 1
-  #         fi            
+  check-version-bump:
+    if: github.ref == 'refs/heads/main'
+    runs-on: ubuntu-latest
+    needs: [ruff-check, test]
+    
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Load PyPI version
+        uses: maybe-hello-world/pyproject-check-version@v4
+        id: version_check
+      
+      - name: check output
+        run: |
+          if [ "${{ steps.version_check.outputs.local_version_is_higher }}" ]; then
+            local=${{ steps.version_check.outputs.local_version }}
+            pypi=${{ steps.version_check.outputs.local_version }}
+          echo "Error: local version($local) <= PyPI($pypi), bump it to publish"
+            exit 1
+          fi            
 
   publish:
     if: github.ref == 'refs/heads/main'
     runs-on: ubuntu-latest
-    needs: [ruff-check, test]
+    needs: [ruff-check, test, check-version-bump]
 
     steps:
       - uses: actions/checkout@v4
